import {Profession} from "./Profession.mjs";
import {ProfessionCategory} from "./ProfessionCategory.mjs";
import {Skill} from "./Skills/Skill.mjs";
import {PhysicalSkills} from "./Skills/PhysicalSkills.mjs";
import {MentalSkills} from "./Skills/MentalSkills.mjs";

export class ProfessionCategories {
    static WOOD() {
        return ProfessionCategory.new("Wood")
            .addProfession(
                Profession.new("Woodcutter")
                    .addSkill(Skill.new("Woodcutting"))
            )
            .addProfession(
                Profession.new("Carpenter")
                    .addSkill(Skill.new("Woodcutting"))
                    .addSkill(Skill.new("Carpentry"))
            )
            .addProfession(
                Profession.new("Bowyer")
                    .addSkill(Skill.new("Woodcutting"))
                    .addSkill(Skill.new("Bowcraft"))
            )
            .addProfession(
                Profession.new("Fletcher")
                    .addSkill(Skill.new("Woodcutting"))
                    .addSkill(Skill.new("Bowcraft"))
            )
            .addProfession(
                Profession.new("Lumberjack")
                    .addSkill(Skill.new("Woodcutting"))
                    .addSkill(Skill.new("Logging"))
            )
            .addProfession(
                Profession.new("Sawyer")
                    .addSkill(Skill.new("Woodcutting"))
                    .addSkill(Skill.new("Logging"))
                    .addSkill(Skill.new("Carpentry"))
            )
    }

    static METAL() {
        return ProfessionCategory.new("Metal")
            .addProfession(
                Profession.new("Miner")
                    .addSkill(Skill.new("Mining"))
                    .addSkill(Skill.new("Digging"))
            )
            .addProfession(
                Profession.new("Blacksmith")
                    .addSkill(Skill.new("Blacksmithing"))
                    .addSkill(Skill.new("Hammering"))
            )
            .addProfession(
                Profession.new("Armorer")
                    .addSkill(Skill.new("Blacksmithing"))
                    .addSkill(Skill.new("Armorsmithing"))
                    .addSkill(Skill.new("Hammering"))
            )
            .addProfession(
                Profession.new("Weaponsmith")
                    .addSkill(Skill.new("Blacksmithing"))
                    .addSkill(Skill.new("Weaponsmithing"))
                    .addSkill(Skill.new("Hammering"))
            )
            .addProfession(
                Profession.new("Jeweler")
                    .addSkill(Skill.new("Blacksmithing"))
                    .addSkill(Skill.new("Jewelcrafting"))
            )
            .addProfession(
                Profession.new("Prospector")
                    .addSkill(Skill.new("Mining"))
                    .addSkill(Skill.new("Prospecting"))
            )
    }

    static LEATHER() {
        return ProfessionCategory.new("Leather")
            .addProfession(
                Profession.new("Tanner")
                    .addSkill(Skill.new("Tanning"))
            )
            .addProfession(
                Profession.new("Leatherworker")
                    .addSkill(Skill.new("Tanning"))
                    .addSkill(Skill.new("Leatherworking"))
            )
            .addProfession(
                Profession.new("Tailor")
                    .addSkill(Skill.new("Tailoring"))
                    .addSkill(Skill.new("Sewing"))
            )
            .addProfession(
                Profession.new("Furrier")
                    .addSkill(Skill.new("Tanning"))
                    .addSkill(Skill.new("Leatherworking"))
                    .addSkill(Skill.new("Sewing"))
            )
            .addProfession(
                Profession.new("Saddler")
                    .addSkill(Skill.new("Tanning"))
                    .addSkill(Skill.new("Leatherworking"))
                    .addSkill(Skill.new("Sewing"))
            )
            .addProfession(
                Profession.new("Skinner")
                    .addSkill(Skill.new("Tanning"))
                    .addSkill(Skill.new("Skinning"))
            )
    }

    static FOOD() {
        return ProfessionCategory.new("Food")
            .addProfession(
                Profession.new("Farmer")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(Skill.new("Driving"))
            )
            .addProfession(
                Profession.new("Cook")
                    .addSkill(PhysicalSkills.Cooking())
                    .addSkill(Skill.new("Cutting"))
                    .addSkill(Skill.new("Baking"))
                    .addSkill(MentalSkills.Herbalism())
            )
            .addProfession(
                Profession.new("Baker")
                    .addSkill(Skill.new("Baking"))
            )
            .addProfession(
                Profession.new("Butcher")
                    .addSkill(Skill.new("Cutting"))
                    .addSkill(Skill.new("Skinning"))
            )
            .addProfession(
                Profession.new("Fisherman")
                    .addSkill(PhysicalSkills.Fishing())
            )
            .addProfession(
                Profession.new("Brewer")
                    .addSkill(PhysicalSkills.Brewing())
            )
            .addProfession(
                Profession.new("Vintner")
                    .addSkill(PhysicalSkills.Brewing())
            )
            .addProfession(
                Profession.new("Gardener")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(Skill.new("Gardening"))
            )
            .addProfession(
                Profession.new("Herbalist")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(Skill.new("Gardening"))
                    .addSkill(MentalSkills.Herbalism())
            )
            .addProfession(
                Profession.new("Miller")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(Skill.new("Milling"))
            )
            .addProfession(
                Profession.new("Beekeeper")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(Skill.new("Beekeeping"))
            )
            .addProfession(
                Profession.new("Cheesemaker")
                    .addSkill(Skill.new("Animal Husbandry"))
                    .addSkill(Skill.new("Cheesemaking"))
            )
            .addProfession(
                Profession.new("Dairyman")
                    .addSkill(Skill.new("Animal Husbandry"))
            )
            .addProfession(
                Profession.new("Distiller")
                    .addSkill(PhysicalSkills.Brewing())
                    .addSkill(PhysicalSkills.Distilling())
            )
            .addProfession(
                Profession.new("Meadmaker")
                    .addSkill(PhysicalSkills.Brewing())
                    .addSkill(PhysicalSkills.Distilling())
            )
    }

    static SERVICE() {
        return ProfessionCategory.new("Service")
            .addProfession(
                Profession.new("Server")
                    .addSkill(MentalSkills.Charisma())
                    .addSkill(PhysicalSkills.Balance())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Bartender")
                    .addSkill(MentalSkills.Charisma())
                    .addSkill(PhysicalSkills.Balance())
                    .addSkill(PhysicalSkills.Mixing())
            )
            .addProfession(
                Profession.new("Innkeeper")
                    .addSkill(MentalSkills.Charisma())
                    .addSkill(PhysicalSkills.Mixing())
                    .addSkill(MentalSkills.Hospitality())
                    .addSkill(PhysicalSkills.Cooking())
            )
            .addProfession(
                Profession.new("Merchant")
                    .addSkill(MentalSkills.Charisma())
                    .addSkill(MentalSkills.Negotiation())
                    .addSkill(MentalSkills.Finance())
            )
            .addProfession(
                Profession.new("Banker")
                    .addSkill(MentalSkills.Charisma().optional())
                    .addSkill(MentalSkills.Finance())
                    .addSkill(MentalSkills.Mathematics())
                    .addSkill(MentalSkills.Negotiation())
            )
            .addProfession(
                Profession.new("Scribe")
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(PhysicalSkills.Listening())
            )
            .addProfession(
                Profession.new("Scholar")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
            )
            .addProfession(
                Profession.new("Librarian")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
            )
            .addProfession(
                Profession.new("Mathematician")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Mathematics())
            )
            .addProfession(
                Profession.new("Teacher")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy())
                    .addSkill(MentalSkills.Patience().optional())
            )
            .addProfession(
                Profession.new("Professor")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Philosopher")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(PhysicalSkills.Calligraphy())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Priest")
                    .addSkill(MentalSkills.Belief())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Politician")
                    .addSkill(MentalSkills.Charisma())
                    .addSkill(MentalSkills.Negotiation())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Sage")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Apothecary")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy())
                    .addSkill(MentalSkills.Herbalism())
            )
            .addProfession(
                Profession.new("Physician")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(MentalSkills.Herbalism())
                    .addSkill(PhysicalSkills.Surgery())
            )
            .addProfession(
                Profession.new("Alchemist")
                    .addSkill(MentalSkills.Literacy().optional())
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Creativity())
                    .addSkill(MentalSkills.Herbalism())
                    .addSkill(Skill.new("Alchemy"))
            )
            .addProfession(
                Profession.new("Astrologer")
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Mathematics().optional())
                    .addSkill(MentalSkills.Creativity())
                    .addSkill(MentalSkills.Astrology())
            )
            .addProfession(
                Profession.new("Astronomer")
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Mathematics().optional())
                    .addSkill(MentalSkills.Astronomy())
            )
            .addProfession(
                Profession.new("Cartographer")
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(MentalSkills.Cartography())
            )
            .addProfession(
                Profession.new("Engineer")
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Drawing())
                    .addSkill(MentalSkills.Engineering())
            )
            .addProfession(
                Profession.new("Architect")
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Drawing())
                    .addSkill(MentalSkills.Creativity().optional())
            )
    }
}