import {Profession} from "./Profession.mjs";
import {ProfessionCategory} from "./ProfessionCategory.mjs";
import {Skill} from "./Skills/Skill.mjs";
import {PhysicalSkills} from "./Skills/PhysicalSkills.mjs";
import {MentalSkills} from "./Skills/MentalSkills.mjs";

export class ProfessionCategories {
    static WOOD() {
        return ProfessionCategory.new("Wood")
            .addProfession(
                Profession.new("Woodcutter")
                    .addSkill(PhysicalSkills.Woodcutting())
            )
            .addProfession(
                Profession.new("Carpenter")
                    .addSkill(PhysicalSkills.Woodcutting())
                    .addSkill(PhysicalSkills.Carpentry())
            )
            .addProfession(
                Profession.new("Bowyer")
                    .addSkill(PhysicalSkills.Woodcutting())
                    .addSkill(PhysicalSkills.Bowcraft())
            )
            .addProfession(
                Profession.new("Fletcher")
                    .addSkill(PhysicalSkills.Woodcutting())
                    .addSkill(PhysicalSkills.Bowcraft())
            )
            .addProfession(
                Profession.new("Lumberjack")
                    .addSkill(PhysicalSkills.Woodcutting())
                    .addSkill(PhysicalSkills.Logging())
            )
            .addProfession(
                Profession.new("Sawyer")
                    .addSkill(PhysicalSkills.Woodcutting())
                    .addSkill(PhysicalSkills.Logging())
                    .addSkill(PhysicalSkills.Carpentry())
            )
    }

    static METAL() {
        return ProfessionCategory.new("Metal")
            .addProfession(
                Profession.new("Miner")
                    .addSkill(PhysicalSkills.Mining())
            )
            .addProfession(
                Profession.new("Blacksmith")
                    .addSkill(PhysicalSkills.Smithing())
            )
            .addProfession(
                Profession.new("Armorer")
                    .addSkill(PhysicalSkills.Smithing())
                    .addSkill(PhysicalSkills.Armorsmithing())
            )
            .addProfession(
                Profession.new("Weaponsmith")
                    .addSkill(PhysicalSkills.Smithing())
                    .addSkill(PhysicalSkills.Weaponsmithing())
            )
            .addProfession(
                Profession.new("Jeweler")
                    .addSkill(PhysicalSkills.Smithing())
                    .addSkill(PhysicalSkills.Jewelcrafting())
            )
            .addProfession(
                Profession.new("Prospector")
                    .addSkill(PhysicalSkills.Mining())
                    .addSkill(MentalSkills.Prospecting())
            )
            .addProfession(
                Profession.new("Smith")
                    .addSkill(PhysicalSkills.Smithing())
            )
    }

    static LEATHER() {
        return ProfessionCategory.new("Leather")
            .addProfession(
                Profession.new("Tanner")
                    .addSkill(PhysicalSkills.Tanning())
            )
            .addProfession(
                Profession.new("Leatherworker")
                    .addSkill(PhysicalSkills.Tanning())
                    .addSkill(PhysicalSkills.Leatherworking())
            )
            .addProfession(
                Profession.new("Tailor")
                    .addSkill(PhysicalSkills.Tailoring())
                    .addSkill(PhysicalSkills.Sewing())
            )
            .addProfession(
                Profession.new("Furrier")
                    .addSkill(PhysicalSkills.Tanning())
                    .addSkill(PhysicalSkills.Leatherworking())
                    .addSkill(PhysicalSkills.Sewing())
            )
            .addProfession(
                Profession.new("Saddler")
                    .addSkill(PhysicalSkills.Tanning())
                    .addSkill(PhysicalSkills.Leatherworking())
                    .addSkill(PhysicalSkills.Sewing())
            )
            .addProfession(
                Profession.new("Skinner")
                    .addSkill(PhysicalSkills.Tanning())
                    .addSkill(PhysicalSkills.Skinning())
            )
    }

    static FOOD() {
        return ProfessionCategory.new("Food")
            .addProfession(
                Profession.new("Farmer")
                    .addSkill(PhysicalSkills.Farming())
            )
            .addProfession(
                Profession.new("Cook")
                    .addSkill(PhysicalSkills.Cooking())
                    .addSkill(PhysicalSkills.Cutting())
                    .addSkill(PhysicalSkills.Baking())
                    .addSkill(MentalSkills.Herbalism())
            )
            .addProfession(
                Profession.new("Baker")
                    .addSkill(Skill.new("Baking"))
            )
            .addProfession(
                Profession.new("Butcher")
                    .addSkill(PhysicalSkills.Cutting())
                    .addSkill(PhysicalSkills.Skinning())
                    .addSkill(PhysicalSkills.Hammering())
            )
            .addProfession(
                Profession.new("Fisherman")
                    .addSkill(PhysicalSkills.Fishing())
            )
            .addProfession(
                Profession.new("Brewer")
                    .addSkill(PhysicalSkills.Brewing())
            )
            .addProfession(
                Profession.new("Vintner")
                    .addSkill(PhysicalSkills.Brewing())
            )
            .addProfession(
                Profession.new("Gardener")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(PhysicalSkills.Gardening())
            )
            .addProfession(
                Profession.new("Herbalist")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(PhysicalSkills.Gardening())
                    .addSkill(MentalSkills.Herbalism())
            )
            .addProfession(
                Profession.new("Miller")
                    .addSkill(PhysicalSkills.Farming())
                    .addSkill(PhysicalSkills.Milling())
            )
            .addProfession(
                Profession.new("Beekeeper")
                    .addSkill(PhysicalSkills.AnimalHusbandry())
                    .addSkill(PhysicalSkills.Beekeeping())
            )
            .addProfession(
                Profession.new("Cheesemaker")
                    .addSkill(PhysicalSkills.AnimalHusbandry())
                    .addSkill(PhysicalSkills.Cheesemaking())
            )
            .addProfession(
                Profession.new("Dairyman")
                    .addSkill(PhysicalSkills.AnimalHusbandry())
            )
            .addProfession(
                Profession.new("Distiller")
                    .addSkill(PhysicalSkills.Brewing())
                    .addSkill(PhysicalSkills.Distilling())
            )
            .addProfession(
                Profession.new("Meadmaker")
                    .addSkill(PhysicalSkills.Brewing())
                    .addSkill(PhysicalSkills.Distilling())
            )
    }

    static SERVICE() {
        return ProfessionCategory.new("Service")
            .addProfession(
                Profession.new("Server")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Charisma().optional())
                    .addSkill(PhysicalSkills.Balance().optional())
                    .addSkill(MentalSkills.Patience().optional())
            )
            .addProfession(
                Profession.new("Storeclerk")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Charisma().optional())
                    .addSkill(MentalSkills.Negotiation().optional())
                    .addSkill(MentalSkills.Patience().optional())
            )
            .addProfession(
                Profession.new("Bartender")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Charisma().optional())
                    .addSkill(PhysicalSkills.Balance().optional())
                    .addSkill(PhysicalSkills.Mixing().optional())
            )
            .addProfession(
                Profession.new("Innkeeper")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Charisma())
                    .addSkill(PhysicalSkills.Mixing().optional())
                    .addSkill(MentalSkills.Hospitality())
                    .addSkill(PhysicalSkills.Cooking())
            )
            .addProfession(
                Profession.new("Merchant")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Charisma().optional())
                    .addSkill(MentalSkills.Negotiation())
                    .addSkill(MentalSkills.Finance())
            )
            .addProfession(
                Profession.new("Banker")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Charisma().optional())
                    .addSkill(MentalSkills.Finance())
                    .addSkill(MentalSkills.Mathematics())
                    .addSkill(MentalSkills.Negotiation())
            )
            .addProfession(
                Profession.new("Scribe")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(PhysicalSkills.Listening())
            )
            .addProfession(
                Profession.new("Scholar")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
            )
            .addProfession(
                Profession.new("Librarian")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
            )
            .addProfession(
                Profession.new("Mathematician")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Mathematics())
            )
            .addProfession(
                Profession.new("Teacher")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(MentalSkills.Authority())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Patience().optional())
            )
            .addProfession(
                Profession.new("Student")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(PhysicalSkills.Writing())
            )
            .addProfession(
                Profession.new("Professor")
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Philosopher")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(PhysicalSkills.Calligraphy())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Priest")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Belief())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Politician")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Charisma())
                    .addSkill(MentalSkills.Negotiation())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Sage")
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Calligraphy())
                    .addSkill(MentalSkills.Patience())
            )
            .addProfession(
                Profession.new("Apothecary")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy())
                    .addSkill(MentalSkills.Herbalism())
            )
            .addProfession(
                Profession.new("Physician")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Literacy())
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(MentalSkills.Herbalism())
                    .addSkill(PhysicalSkills.Surgery())
            )
            .addProfession(
                Profession.new("Alchemist")
                    .addSkill(MentalSkills.Literacy().optional())
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Creativity())
                    .addSkill(MentalSkills.Herbalism())
                    .addSkill(MentalSkills.Alchemy())
            )
            .addProfession(
                Profession.new("Astrologer")
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Mathematics().optional())
                    .addSkill(MentalSkills.Creativity())
                    .addSkill(MentalSkills.Astrology())
            )
            .addProfession(
                Profession.new("Astronomer")
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(PhysicalSkills.Calligraphy().optional())
                    .addSkill(MentalSkills.Mathematics().optional())
                    .addSkill(MentalSkills.Astronomy())
            )
            .addProfession(
                Profession.new("Cartographer")
                    .addSkill(MentalSkills.Research().optional())
                    .addSkill(MentalSkills.Cartography())
            )
            .addProfession(
                Profession.new("Engineer")
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Drawing())
                    .addSkill(MentalSkills.Engineering())
            )
            .addProfession(
                Profession.new("Architect")
                    .addSkill(MentalSkills.Research())
                    .addSkill(PhysicalSkills.Drawing())
                    .addSkill(MentalSkills.Creativity().optional())
            )
            .addProfession(
                Profession.new("Doctor")
                    .addSkill(PhysicalSkills.Listening())
                    .addSkill(PhysicalSkills.Speaking())
                    .addSkill(MentalSkills.Medicine())
            )
    }
}